name: Android Master Release Workflow.

on:
  push:
    branches:
      - 'master'

jobs:
  test_app_and_generate_apk_release:
    name: Run Android Tests and Generates APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Run UI Tests - API 29
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Run UI Tests - API 19
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 19
          script: ./gradlew connectedCheck

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Together Button - Example APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Get APK version name
        run: echo ::set-env name=VERSION_NAME::$(gradle -q printVersionName)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: Release v${{ env.VERSION_NAME }}
          body_path: release-notes/CHANGELOG.md
          draft: true
          prerelease: false