name: Android Master - Pull Request Workflow.

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test_release_app:
    name: Run Android Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace