name: Android Develop - Pull Request Workflow.

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  test_develop_app:
    name: Run Android Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Run UI Tests - API 26
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - name: Run UI Tests - API 19
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 19
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace