name: Android Master - Pull Request Workflow.

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test_release_app:
    name: Run Android Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace

      - name: Run UI Tests - API 29
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Run UI Tests - API 19
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 19
          script: ./gradlew connectedCheck

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace